=== joydip-git/oracle_21stJulyBatch_repo/Codes/XML/schema-app/contact-schema.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="contacts">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="contact">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string" />
                            <xs:element name="email" type="xs:string" />
                            <xs:element name="mobile" type="xs:long" />
                            <xs:element name="landline" type="xs:long" maxOccurs="1" minOccurs="0" />
                            <xs:element name="address">
                                <xs:sequence>
                                    <xs:element name="door_no" type="xs:int" />
                                    <xs:element name="street" type="xs:string" />
                                    <xs:element name="city" type="xs:string" />
                                    <xs:element name="state" type="xs:string" />
                                    <xs:element name="country" type="xs:string" default="IND" minOccurs="0" maxOccurs="1" />
                                    <xs:element name="pinCode" type="xs:long" />
                                    <xs:element name="mode_of_contact" type="xs:string" fixed="mobile" />
                                </xs:sequence>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="contact_id" type="xs:string" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== joydip-git/oracle_21stJulyBatch_repo/Codes/XML/schema-app/contacts.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- <?xml-model href="./contact-schema.xsd" type="application/xml" schematypens="http://www.w3.org/2001/XMLSchema"?> -->
<contacts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./contact-schema.xsd">
    <contact contact_id="c101">
        <name>Joydip</name>
        <email></email>
        <mobile>9090909090</mobile>
        <address>
            <door_no>123</door_no>
            <street>2nd Main</street>
            <city>Bangalore</city>
            <state>KA</state>
            <country>IND</country>
            <pinCode>123456</pinCode>
            <mode_of_contact>mobile</mode_of_contact>
        </address>
    </contact>
</contacts>
