=== joydip-git/oracle_21stJulyBatch_repo/Codes/XML/dtd-app/employees-dtd.dtd
<!ELEMENT products (product+)>
<!ELEMENT product (name,price,description,ISBN,reviews, manufacturer, company?)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT ISBN (ISBN-8 | ISBN-10)>
<!ELEMENT ISBN-8 (#PCDATA)>
<!ELEMENT ISBN-10 (#PCDATA)>
<!ELEMENT reviews (review*)>
<!ELEMENT review (#PCDATA|comment|reviewText)*>
<!ELEMENT comment (#PCDATA)>
<!ELEMENT reviewText (#PCDATA)>
<!ELEMENT manufacturer ANY>
<!ELEMENT company (#PCDATA)>

=== joydip-git/oracle_21stJulyBatch_repo/Codes/XML/dtd-app/employees.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE products SYSTEM "./employees-dtd.dtd">
<!-- <!DOCTYPE root-element 
[

]> -->
<products>
    <product>
        <name>Dell XPS 15</name>
        <price>120000</price>
        <description>new laptop from dell</description>
        <ISBN>
            <ISBN-10>1234567890</ISBN-10>
        </ISBN>
        <reviews>
            <review>
                Nice laptop
            </review>
            <review>
                <comment>
                    superb performance
                </comment>
            </review>
            <review>
                <reviewText>
                    worth money
                </reviewText>
            </review>
        </reviews>
        <manufacturer>
            <company>
                Hitachi
            </company>
        </manufacturer>
    </product>
</products>
